# Generated by Django 5.0 on 2023-12-05 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clientID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('phoneNo', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('serviceName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('workerID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('phoneNo', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('requestID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('requestDate', models.DateField()),
                ('status', models.IntegerField()),
                ('dateAccepted', models.DateField()),
                ('dateFinished', models.DateField()),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.client')),
                ('serviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.service')),
                ('workerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.worker')),
            ],
        ),
        migrations.CreateModel(
            name='RateService',
            fields=[
                ('rateID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rateValue', models.IntegerField()),
                ('comment', models.CharField(max_length=500)),
                ('requestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='PostService',
            fields=[
                ('postID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('serviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.service')),
                ('workerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('paymentDate', models.DateField()),
                ('amountDate', models.FloatField()),
                ('amountPaid', models.FloatField()),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.client')),
                ('requestID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.servicerequest')),
                ('workerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.worker')),
            ],
        ),
    ]
