# Generated by Django 5.0 on 2023-12-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_payment_paymentid_alter_postservice_postid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
