# Generated by Django 5.0 on 2023-12-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_progress_remove_postservice_serviceid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='CompletedStatus',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
