# Generated by Django 5.0 on 2023-12-06 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_transaction_progressid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ClientID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.client'),
        ),
    ]
