# Generated by Django 4.2.5 on 2023-12-06 12:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_transaction_clientid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentID', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('paymentDate', models.DateField()),
                ('amountDate', models.FloatField()),
                ('amountPaid', models.FloatField()),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.client')),
            ],
        ),
        migrations.CreateModel(
            name='PostService',
            fields=[
                ('postID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', help_text='Title of the service post', max_length=100)),
                ('description', models.TextField(default='', help_text='Description of the service')),
                ('location', models.CharField(default='', max_length=255)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the post was created')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RateService',
            fields=[
                ('rateID', models.AutoField(primary_key=True, serialize=False)),
                ('rateValue', models.IntegerField()),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceID', models.AutoField(primary_key=True, serialize=False)),
                ('serviceName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('requestID', models.AutoField(primary_key=True, serialize=False)),
                ('requestDate', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10)),
                ('dateAccepted', models.DateField(blank=True, null=True)),
                ('dateFinished', models.DateField(blank=True, null=True)),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.client')),
                ('serviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.service')),
                ('workerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.worker')),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='ClientID',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='WorkerID',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='TransactionID',
        ),
        migrations.RemoveField(
            model_name='services',
            name='WorkerID',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ClientID',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ProgressID',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ServiceID',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='rateservice',
            name='requestID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.servicerequest'),
        ),
        migrations.AddField(
            model_name='postservice',
            name='serviceID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.service'),
        ),
        migrations.AddField(
            model_name='postservice',
            name='workerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.worker'),
        ),
        migrations.AddField(
            model_name='payment',
            name='requestID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.servicerequest'),
        ),
        migrations.AddField(
            model_name='payment',
            name='workerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.worker'),
        ),
    ]
