# Generated by Django 5.0 on 2023-12-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_payment_postservice_rateservice_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=199),
        ),
        migrations.AlterField(
            model_name='service',
            name='serviceName',
            field=models.CharField(max_length=49),
        ),
    ]
